### ISSUE TITLE
Missing README paragraph for SI-H2

### ISSUE THREAD

**Issue by trebmuh** [guysherman/si-plugins#15]
It looks like the 0.3.0 version brings up a SI-H2 plugin but there is no explanation of it in the README.md
It'd be great if you can write something there.
Thanks.

**Comment by guysherman** [comment]
Good call, I will probably only get around to it next weekend.

**Comment by guysherman** [comment]
Done.

**Comment by trebmuh** [comment]
Awesome, thank you.
