### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by trebmuh** [guysherman/si-plugins#16]
Trying to build from GIT master, I've got :

```
 make[1]: Entering directory '/tmp/buildd/si-plugins-0.3.0+git20161030~d78f0bc'
cc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-z,relro  test.c   -o test
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

Any hint?

PS : still debian Jessie up-to-date

**Comment by guysherman** [comment]
you may need to edit your .gitmodules file and point the dpf submodule to git@github.com:guysherman/dpf instead of git@github.com:DHISTRO/dpf, that's the only major change I've made recently.

**Comment by trebmuh** [comment]
This is what I did. Is there anyway to switch it back to the DISTHRO version of dpf ?

**Comment by guysherman** [comment]
Oh, I know what that is... not sure why it is building test.c, just delete that file, you don't want it anyway, I shouldn't have left that in.

**Comment by guysherman** [comment]
I have pushed a commit which removed that file.

**Comment by trebmuh** [comment]
Sweet. Just did a rebuild and it works as expected. Thanks.
(Hence, I'm closing this thread)
