### ISSUE TITLE
Build without GUI

### ISSUE THREAD

**Issue by trebmuh** [guysherman/si-plugins#7]
Hi, I've been trying to build from a fresh git clone but I've got no GUI. Any idea ?
(Debian Jessie updated here)

**Comment by trebmuh** [comment]
Nervermind, I simply forgot some build dependencies. It works fine now.
That said, it could be great if a configure step could check and tell what is going to be constructed.

**Comment by guysherman** [comment]
Thanks for the feedback. I've added some warnings into the makefile. I don't have a configure script at this stage, but at least you can look back through your build ouput now and find out why you didn't get a GUI (or standalone exe, or osc, etc).

**Comment by trebmuh** [comment]
:+1:
