### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by trebmuh** [guysherman/si-plugins#8]
It does look that both of the plugins are using a lot of CPU in comparison with other LV2 plugins.

**Comment by guysherman** [comment]
Have you got a bit more info about this? Do you have some other distortion plugins in mind that I could compare to? I suspect it is to do with the oversampling, perhaps I can use a faster mode.

**Comment by guysherman** [comment]
I did some profiling and found that 99.9% of the time was being spent in src_process, so I have lowered the settings.

@trebmuh I have pushed a change which uses the 'fastest' quality setting for libsamplerate. I also upped the oversampling to 4x to mitigate the drop in quality. CPU usage on my machine has dropped from ~18% to ~4% for SI-D1. I expect a similar drop for SI-D2.

**Comment by trebmuh** [comment]
Hi @guysherman : That's much better here now. Thanks you.
Some other plugins you can compare to are:
Calf : crusher, exciter,  saturator, tape simulator
Swh : chebyshev
Deathcrush-lv2
SWH : decimator, diode processor, foldover distortion
Guitarix : distortion, GXfuzz, GxFuzzFaceFuller, GxFuzzFaceJH2, GxFuzzMaster, GxHogsFoot, GxHornet, GxMuff, GxMultiBandDistorsion, GxRedeye Chump and Big Chump, GxRedeye Vibro Chump, GxScreamingBird, GxSustainer, GxTiltTone, GxTubeScreamer
Newtonator
... and others...

Hope that helps.
Olivier
